"use strict";

function printSomething(counter) {
  for (let i = 1; i < counter; i++) {
    //Pretending to do something
    console.log(i);
  }
  console.log("All numbers printed.");
  let p = document.getElementById("myParagraph");
  p.textContent = "This text is generated by JavaScript.";
}

function sendPopup() {
  alert("You pressed the button");
}

document.getElementById("myButton").addEventListener("click", sendPopup);
printSomething(0);
