"use strict";

async function printSomething(counter) {
  for (let i = 1; i < counter; i++) {
    //Pretending to do something
    console.log(i);
    if (i % 100000 === 0) {
      await new Promise((resolve) => setTimeout(resolve, 0));
    }
  }
  console.log("All numbers printed.");
  let p = document.getElementById("myParagraph");
  p.textContent = "This text is generated by JavaScript.";
}

function sendPopup() {
  alert("You pressed the button");
}

document.getElementById("myButton").addEventListener("click", sendPopup);
printSomething(5000000);
